tblyear_index:
    path:     /
    defaults: { _controller: "VatencioSgisBundle:Default:index" }
    methods:  GET

tblyear_show:
    path:     /{id}/show
    defaults: { _controller: "VatencioSgisBundle:Tblyear:show" }
    methods:  GET

tblyear_new:
    path:     /new
    defaults: { _controller: "VatencioSgisBundle:Tblyear:new" }
    methods:  [GET, POST]

tblyear_edit:
    path:     /{id}/edit
    defaults: { _controller: "VatencioSgisBundle:Tblyear:edit" }
    methods:  [GET, POST]

tblyear_delete:
    path:     /{id}/delete
    defaults: { _controller: "VatencioSgisBundle:Tblyear:delete" }
    methods:  DELETE
