tblcurso_index:
    path:     /
    defaults: { _controller: "VatencioSgisBundle:Tblcurso:index" }
    methods:  GET

tblcurso_show:
    path:     /{id}/show
    defaults: { _controller: "VatencioSgisBundle:Tblcurso:show" }
    methods:  GET

tblcurso_new:
    path:     /new
    defaults: { _controller: "VatencioSgisBundle:Tblcurso:new" }
    methods:  [GET, POST]

tblcurso_edit:
    path:     /{id}/edit
    defaults: { _controller: "VatencioSgisBundle:Tblcurso:edit" }
    methods:  [GET, POST]

tblcurso_delete:
    path:     /{id}/delete
    defaults: { _controller: "VatencioSgisBundle:Tblcurso:delete" }
    methods:  DELETE
