tblmateriaestudiante_index:
    path:     /
    defaults: { _controller: "VatencioSgisBundle:Tblmateriaestudiante:index" }
    methods:  GET

tblmateriaestudiante_show:
    path:     /{id}/show
    defaults: { _controller: "VatencioSgisBundle:Tblmateriaestudiante:show" }
    methods:  GET

tblmateriaestudiante_new:
    path:     /new
    defaults: { _controller: "VatencioSgisBundle:Tblmateriaestudiante:new" }
    methods:  [GET, POST]

tblmateriaestudiante_edit:
    path:     /{id}/edit
    defaults: { _controller: "VatencioSgisBundle:Tblmateriaestudiante:edit" }
    methods:  [GET, POST]

tblmateriaestudiante_delete:
    path:     /{id}/delete
    defaults: { _controller: "VatencioSgisBundle:Tblmateriaestudiante:delete" }
    methods:  DELETE
