tblnota_index:
    path:     /
    defaults: { _controller: "VatencioSgisBundle:Tblnota:index" }
    methods:  GET

tblnota_show:
    path:     /{id}/show
    defaults: { _controller: "VatencioSgisBundle:Tblnota:show" }
    methods:  GET

tblnota_new:
    path:     /new
    defaults: { _controller: "VatencioSgisBundle:Tblnota:new" }
    methods:  [GET, POST]

tblnota_edit:
    path:     /{id}/edit
    defaults: { _controller: "VatencioSgisBundle:Tblnota:edit" }
    methods:  [GET, POST]

tblnota_delete:
    path:     /{id}/delete
    defaults: { _controller: "VatencioSgisBundle:Tblnota:delete" }
    methods:  DELETE
