tblpersona_index:
    path:     /
    defaults: { _controller: "VatencioSgisBundle:Tblpersona:index" }
    methods:  GET

tblpersona_show:
    path:     /{id}/show
    defaults: { _controller: "VatencioSgisBundle:Tblpersona:show" }
    methods:  GET

tblpersona_new:
    path:     /new
    defaults: { _controller: "VatencioSgisBundle:Tblpersona:new" }
    methods:  [GET, POST]

tblpersona_edit:
    path:     /{id}/edit
    defaults: { _controller: "VatencioSgisBundle:Tblpersona:edit" }
    methods:  [GET, POST]

tblpersona_delete:
    path:     /{id}/delete
    defaults: { _controller: "VatencioSgisBundle:Tblpersona:delete" }
    methods:  DELETE