# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:
#    encoders:
#         FOS\UserBundle\Model\UserInterface: sha512
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt
    # http://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN
#    providers:
#        in_memory:
#            memory: ~
    providers:
        fos_userbundle:
            id: fos_user.user_provider.username
#    providers:
#        fos_userbundle:
#            id: fos_user.user_manager 
#    firewalls:
#        main:
#            pattern: ^/
#            form_login:
#                provider: fos_userbundle
#                csrf_token_generator: security.csrf.token_manager
#                # if you are using Symfony < 2.8, use the following config instead:
#                # csrf_provider: form.csrf_provider
#
#            logout:       true
#            anonymous:    true

    firewalls:
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                #csrf_provider: form.csrf_provider
                csrf_token_generator: security.csrf.token_manager
                check_path: /login_check
                default_target_path: /  
            logout:
                path:   /logout
                target: /login
            anonymous: true
            security: true
#    firewalls:
#        # disables authentication for assets and the profiler, adapt it according to your needs
#        dev:
#            pattern: ^/(_(profiler|wdt)|css|images|js)/
#            security: false
#
#        main:
#            anonymous: ~

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
       # - { path: ^/register, role: [ROLE_ADMIN, ROLE_CLIENTE]}
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY}
        - { path: ^/resetting, role: [ROLE_ADMIN] }
        - { path: ^/admin*, roles: [ROLE_ADMIN] }
       # - { path: ^/*, roles: [ROLE_ADMIN, ROLE_CLIENTE, ROLE_EVALUADO, ROLE_ASISTENTE, ROLE_INFORMES, ROLE_CITACIONES]}
        - { path: ^/, roles: IS_AUTHENTICATED_ANONYMOUSLY}
        # disables authentication for assets and the profiler, adapt it according to your needs
        #dev:
        #    pattern: ^/(_(profiler|wdt)|css|images|js)/
        #    security: false

        #main:
        #    anonymous: ~
            # activate different ways to authenticate

            # http_basic: ~
            # http://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate

            # form_login: ~
            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html