# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
    app.form.registration:
            class: Vatencio\SgisBundle\Form\RegistrationType
            tags:
                - { name: form.type, alias: app_user_registration }
                
    vatencio_sgis.form.type.sexo:
        class: Vatencio\SgisBundle\Form\Type\SexoType
        arguments:
            - "%array_sexo%"
        tags:
            - { name: form.type }