Vatencio\SgisBundle\Entity\FosUser:
    type: entity
    table: fos_user
    uniqueConstraints:
        UNIQ_957A647992FC23A8:
            columns:
                - username_canonical
        UNIQ_957A6479A0D96FBF:
            columns:
                - email_canonical
        UNIQ_957A6479C05FB297:
            columns:
                - confirmation_token
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        username:
            type: string
            nullable: false
            length: 180
            options:
                fixed: false
        usernameCanonical:
            type: string
            nullable: false
            length: 180
            options:
                fixed: false
            column: username_canonical
        email:
            type: string
            nullable: false
            length: 180
            options:
                fixed: false
        emailCanonical:
            type: string
            nullable: false
            length: 180
            options:
                fixed: false
            column: email_canonical
        enabled:
            type: boolean
            nullable: false
        salt:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
        password:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        lastLogin:
            type: datetime
            nullable: true
            column: last_login
        confirmationToken:
            type: string
            nullable: true
            length: 180
            options:
                fixed: false
            column: confirmation_token
        passwordRequestedAt:
            type: datetime
            nullable: true
            column: password_requested_at
        roles:
            type: array
            nullable: false
            length: null
            options:
                fixed: false
    lifecycleCallbacks: {  }
