Vatencio\SgisBundle\Entity\Tbldocenteinstitucion:
    type: entity
    table: tbldocenteinstitucion
    indexes:
        intIdDocente:
            columns:
                - intIdDocente
        intIdInstitucion:
            columns:
                - intIdInstitucion
    id:
        intiddocenteinstitucion:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: intIdDocenteInstitucion
            generator:
                strategy: IDENTITY
    fields:
        dtmcreacion:
            type: datetime
            nullable: true
            column: dtmCreacion
        strcreacion:
            type: string
            nullable: true
            length: 45
            options:
                fixed: false
            column: strCreacion
        dtmactualizacion:
            type: datetime
            nullable: true
            column: dtmActualizacion
        stractualizacion:
            type: string
            nullable: true
            length: 45
            options:
                fixed: false
            column: strActualizacion
    manyToOne:
        intidinstitucion:
            targetEntity: Tblinstitucion
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                intIdInstitucion:
                    referencedColumnName: intIdInstitucion
            orphanRemoval: false
        intiddocente:
            targetEntity: Tbldocente
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                intIdDocente:
                    referencedColumnName: intIdDocente
            orphanRemoval: false
    lifecycleCallbacks: {  }
