Vatencio\SgisBundle\Entity\Tblmateria:
    type: entity
    table: tblmateria
    id:
        intidmateria:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: intIdMateria
            generator:
                strategy: IDENTITY
    fields:
        strnombre:
            type: string
            nullable: false
            length: 100
            options:
                fixed: false
            column: strNombre
        isactive:
            type: boolean
            nullable: false
            column: isActive
        dtmcreacion:
            type: datetime
            nullable: true
            column: dtmCreacion
        strcreacion:
            type: string
            nullable: true
            length: 45
            options:
                fixed: false
            column: strCreacion
        dtmactualizacion:
            type: datetime
            nullable: true
            column: dtmActualizacion
        stractualizacion:
            type: string
            nullable: true
            length: 45
            options:
                fixed: false
            column: strActualizacion
    lifecycleCallbacks: {  }
