Vatencio\SgisBundle\Entity\Tblpermiso:
    type: entity
    table: tblpermiso
    indexes:
        intIdRole:
            columns:
                - intIdRole
        intIdMenu:
            columns:
                - intIdMenu
    id:
        intidpermiso:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: intIdPermiso
            generator:
                strategy: IDENTITY
    fields:
        strnombre:
            type: string
            nullable: false
            length: 100
            options:
                fixed: false
            column: strNombre
        strdescripcion:
            type: string
            nullable: true
            length: 1000
            options:
                fixed: false
            column: strDescripcion
        dtmcreacion:
            type: datetime
            nullable: true
            column: dtmCreacion
        strcreacion:
            type: string
            nullable: true
            length: 45
            options:
                fixed: false
            column: strCreacion
        dtmactualizacion:
            type: datetime
            nullable: true
            column: dtmActualizacion
        stractualizacion:
            type: string
            nullable: true
            length: 45
            options:
                fixed: false
            column: strActualizacion
    manyToOne:
        intidrole:
            targetEntity: Tblrole
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                intIdRole:
                    referencedColumnName: intIdRol
            orphanRemoval: false
        intidmenu:
            targetEntity: Tblmenu
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                intIdMenu:
                    referencedColumnName: intIdMenu
            orphanRemoval: false
    lifecycleCallbacks: {  }
